#!/usr/bin/env python3
"""Export reviewed KillerMUD lore articles as deterministic Markdown."""

from __future__ import annotations

import argparse
import json
import re
import sys
from pathlib import Path
from typing import Any


EXPORT_MANIFEST = ".generated-files.json"
GENERATED_NOTICE = "<!-- Generated from lore/records/*.jsonl. Do not edit this file directly. -->"
SAFE_FILE_PATTERN = re.compile(r"^[a-z0-9][a-z0-9-]*\.md$")
CATEGORY_LABELS = {
    "city": "Miasta",
    "landmark": "Miejsca",
    "region": "Regiony",
    "settlement": "Osady",
}


def load_records(lore_root: Path) -> list[dict[str, Any]]:
    manifest = json.loads((lore_root / "manifest.json").read_text(encoding="utf-8"))
    records: list[dict[str, Any]] = []
    for relative in manifest.get("recordFiles", []):
        path = lore_root / relative
        for line_number, raw_line in enumerate(path.read_text(encoding="utf-8").splitlines(), 1):
            if not raw_line.strip():
                continue
            try:
                records.append(json.loads(raw_line))
            except json.JSONDecodeError as exc:
                raise ValueError(f"Invalid JSONL at {path}:{line_number}: {exc}") from exc
    return records


def article_filename(article_id: str) -> str:
    _, separator, suffix = article_id.partition(":")
    if not separator or not suffix:
        raise ValueError(f"Article id has no type prefix: {article_id}")
    filename = f"{suffix}.md"
    if not SAFE_FILE_PATTERN.fullmatch(filename):
        raise ValueError(f"Article id cannot produce a safe Markdown filename: {article_id}")
    return filename


def record_label(record: dict[str, Any] | None, fallback: str) -> str:
    if record is None:
        return fallback
    return str(record.get("title") or record.get("name") or record.get("summary") or fallback)


def source_key(source: dict[str, Any]) -> str:
    return json.dumps(source, ensure_ascii=False, separators=(",", ":"), sort_keys=True)


def format_source(source: dict[str, Any]) -> str:
    location = [f"`{source['file']}`"]
    if source.get("section"):
        location.append(str(source["section"]))
    if source.get("vnum") is not None:
        location.append(f"vnum {source['vnum']}")
    if source.get("field"):
        location.append(str(source["field"]))
    if source.get("keyword"):
        location.append(f"keyword `{source['keyword']}`")
    result = " — ".join(location)
    if source.get("excerpt"):
        result += f": „{str(source['excerpt']).strip()}”"
    return result


def render_article(
    article: dict[str, Any],
    records_by_id: dict[str, dict[str, Any]],
    article_by_entity: dict[str, dict[str, Any]],
    filenames: dict[str, str],
) -> str:
    lines = [GENERATED_NOTICE, "", f"# {article['title']}", "", article["summary"], ""]
    lines.extend(
        [
            "## Metadane",
            "",
            f"- ID artykułu: `{article['id']}`",
            f"- Encja: `{article['entityId']}`",
            f"- Status: `{article['status']}`",
            f"- Widoczność: `{article['visibility']}`",
            f"- Poziom spoilerów: `{article['spoilerLevel']}`",
            "",
        ]
    )

    sources: dict[str, dict[str, Any]] = {}
    for section in article.get("sections", []):
        lines.extend([f"## {section['title']}", "", section["content"], ""])
        for source in section.get("sourceRefs", []):
            sources.setdefault(source_key(source), source)

    related_ids = article.get("relatedIds", [])
    if related_ids:
        lines.extend(["## Powiązania", ""])
        for related_id in related_ids:
            related = records_by_id.get(related_id)
            label = record_label(related, related_id)
            linked_article = article_by_entity.get(related_id)
            if linked_article is not None:
                lines.append(f"- [{label}]({filenames[linked_article['id']]}) — `{related_id}`")
            else:
                lines.append(f"- {label} — `{related_id}`")
        lines.append("")

    map_references = article.get("mapReferences", {})
    if map_references:
        lines.extend(["## Odniesienia mapy", ""])
        if map_references.get("regionId") is not None:
            lines.append(f"- Region mapy: `{map_references['regionId']}`")
        if map_references.get("areaFiles"):
            lines.append("- Pliki krain: " + ", ".join(f"`{item}`" for item in map_references["areaFiles"]))
        if map_references.get("roomVnums"):
            lines.append("- VNUM-y pomieszczeń: " + ", ".join(f"`{item}`" for item in map_references["roomVnums"]))
        lines.append("")

    if sources:
        lines.extend(["## Źródła", ""])
        for source in sources.values():
            lines.append(f"- {format_source(source)}")
        lines.append("")

    return "\n".join(lines).rstrip() + "\n"


def render_index(articles: list[dict[str, Any]], filenames: dict[str, str]) -> str:
    lines = [GENERATED_NOTICE, "", "# Lore KillerMUD", "", "Czytelny katalog artykułów generowany z kanonicznych rekordów JSONL.", ""]
    current_category: str | None = None
    for article in articles:
        category = str(article["category"])
        if category != current_category:
            if current_category is not None:
                lines.append("")
            heading = CATEGORY_LABELS.get(category, "Pozostałe")
            lines.extend([f"## {heading}", ""])
            current_category = category
        lines.append(f"- [{article['title']}]({filenames[article['id']]}) — {article['summary']}")
    return "\n".join(lines).rstrip() + "\n"


def write_text_atomic(path: Path, content: str) -> None:
    temporary = path.with_name(f".{path.name}.tmp")
    temporary.write_text(content, encoding="utf-8", newline="\n")
    temporary.replace(path)


def load_previous_files(output_dir: Path) -> set[str]:
    path = output_dir / EXPORT_MANIFEST
    if not path.exists():
        return set()
    data = json.loads(path.read_text(encoding="utf-8"))
    files = data.get("files", [])
    if not isinstance(files, list) or not all(isinstance(item, str) for item in files):
        raise ValueError(f"Invalid generated file manifest: {path}")
    return set(files)


def export_markdown(lore_root: Path, output_dir: Path) -> tuple[int, int]:
    records = load_records(lore_root)
    records_by_id = {record["id"]: record for record in records}
    articles = sorted(
        (
            record
            for record in records
            if record.get("recordType") == "article" and record.get("status") in ("reviewed", "canonical")
        ),
        key=lambda item: (str(item["category"]).casefold(), str(item["title"]).casefold(), item["id"]),
    )
    filenames = {article["id"]: article_filename(article["id"]) for article in articles}
    if len(set(filenames.values())) != len(filenames):
        raise ValueError("Article ids produce duplicate Markdown filenames")
    article_by_entity = {article["entityId"]: article for article in articles}

    output_dir.mkdir(parents=True, exist_ok=True)
    generated: dict[str, str] = {"index.md": render_index(articles, filenames)}
    for article in articles:
        generated[filenames[article["id"]]] = render_article(article, records_by_id, article_by_entity, filenames)

    previous_files = load_previous_files(output_dir)
    current_files = set(generated)
    stale_files = previous_files - current_files
    for filename in stale_files:
        if not SAFE_FILE_PATTERN.fullmatch(filename) and filename != "index.md":
            raise ValueError(f"Refusing to remove unsafe generated path: {filename}")
        stale_path = output_dir / filename
        if stale_path.is_file():
            stale_path.unlink()

    for filename, content in sorted(generated.items()):
        write_text_atomic(output_dir / filename, content)

    export_manifest = {
        "schemaVersion": 1,
        "generator": "build-killermud-lore/export_lore_markdown.py",
        "files": sorted(current_files),
        "articleIds": [article["id"] for article in articles],
    }
    write_text_atomic(
        output_dir / EXPORT_MANIFEST,
        json.dumps(export_manifest, ensure_ascii=False, indent=2, sort_keys=True) + "\n",
    )
    return len(articles), len(stale_files)


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--lore-root", type=Path, default=Path("lore"))
    parser.add_argument("--output-dir", type=Path, default=Path("lore/dist/markdown"))
    return parser.parse_args()


def main() -> int:
    try:
        args = parse_args()
        article_count, stale_count = export_markdown(args.lore_root, args.output_dir)
        print(f"Markdown exported: {article_count} article(s), {stale_count} stale file(s) removed.")
        return 0
    except (KeyError, OSError, ValueError, json.JSONDecodeError) as exc:
        print(f"export_lore_markdown: {exc}", file=sys.stderr)
        return 1


if __name__ == "__main__":
    raise SystemExit(main())
